"""signatures added

Revision ID: 8f4cdc5b39d1
Revises: 1b1fa51f2af5
Create Date: 2025-07-02 11:31:47.187382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4cdc5b39d1'
down_revision: Union[str, None] = '1b1fa51f2af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_agreements', sa.Column('agent_a_signature', sa.String(length=255), nullable=True))
    op.add_column('agent_agreements', sa.Column('agent_b_signature', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_agreements', 'agent_b_signature')
    op.drop_column('agent_agreements', 'agent_a_signature')
    # ### end Alembic commands ###
